### ISSUE TITLE
Problem building DEVSimPy

### ISSUE THREAD

**Issue by allanc1** [capocchi/DEVSimPy#119]
Hi
I am trying to install the software in Ubuntu 20.04 withe Anaconda.The install process proceeds and then gives the following errors:
Running setup.py install for wxPython ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2sy7qrs8/wxPython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2sy7qrs8/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5tswwk_r/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/allan/.local/include/python3.8/wxPython                                                         
         cwd: /tmp/pip-install-2sy7qrs8/wxPython/
and
 Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2sy7qrs8/wxPython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2sy7qrs8/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5tswwk_r/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/allan/.local/include/python3.8/wxPython Check the logs for full command output.

Any suggestions to fix would be much appreciated.

Regards

**Comment by capocchi** [comment]
Hi,

You can find below, the process to install DEVSimPy from a termina for python 3.7:

1/ Install miniconda (with the script downloaded from the site)
2/ Create python virtual env (python 3.7) : 
$ conda create -n py37 python=3.7
3/ Activate the env: 
$ conda activate py37
4/ Install pip and git: 
$ sudo apt install python-pip git
5/ Download DEVSimPy using git: 
$ git clone --recurse-submodules -b version-4.0 --depth=1 https://github.com/capocchi/DEVSimPy.git
6/ Clean the repository: 
$ git fetch --unshallow
7 /Go to https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ and dowload the appropriate wxPython .whl file.
8 /Install the wxPython package from the whl file: 
$ pip install <wxPython.whl>
9/ Go to the DEVSimPy directory and install requirements: 
$ pip install -r requirements.txt
10/ Launch DEVSimPy: 
$ python devsimpy.py

Please feel free to contact me if you have any issues. 

Best.

**Comment by allanc1** [comment]
Thanks, much appreciated. It all worked as expected until I tried to run devsimpy when I get:
  File "devsimpy.py", line 81, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

I understand that python-wxtools is requirement to allow the import wx. This is not available in pip or conda, but installing it from the Ubuntu repository did not fix this error.

Kind regards
Allan

**Comment by capocchi** [comment]
Did you install wx with: pip install wxPython-4.1.0-cp38-cp38-linux_x86_64.whl ?

Also, an XUbuntu 19.10 virtual machine including DEVSimPy can be donwloaded from DEVSimPy-on-XUbuntu19.10.ova. The login and password of the distribution (root) are: devsimpy-user/devsimpy. If you want to have the latest version of DEVSimPy, please execute 'git pull' in the DEVSimPy directory before starting or start DEVSimPy by double clicking on the desktop icon and go to Help->Update->From Git Repository (pull).

**Comment by allanc1** [comment]
Hi
Your help is much appreciated, but the issue seems to be due to wxPython for Ubuntu Focal requiring Python 3.8 but Anaconda only supplying Python 3.7. I tried to create a py38 environment but this did not resolve the issue. I then uninstalled Anaconda and when for an entirely pip based installation based on py3.8. This progressed but threw new errors:
  File "devsimpy.py", line 178, in <module>
    import Container
  File "/home/allan/Downloads/DEVSimPy/Container.py", line 70, in <module>
    import ZipManager
  File "/home/allan/Downloads/DEVSimPy/ZipManager.py", line 27, in <module>
    from PluginManager import PluginManager #trigger_event
ModuleNotFoundError: No module named 'PluginManager'

It would seem  scripts do not know from where to fetch the modules.

Kind regards

Allan

**Comment by capocchi** [comment]
Hi,
Oups, I have fixed the case on case insensitive filesystems into git (when I merge from Version-4 to Master). 
Try to pull your repo now.
Best.

**Comment by allanc1** [comment]
Hi
Further progress, I get a splash screen but then the following errors:

File "/home/allan/.local/lib/python3.8/site-packages/wx/core.py", line 2311, in Notify
    self.notify()
  File "/home/allan/.local/lib/python3.8/site-packages/wx/core.py", line 3508, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "devsimpy.py", line 2269, in ShowMain
    self.app.frame = MainApplication(None, wx.NewIdRef(), 'DEVSimPy %s'%__version__)
  File "devsimpy.py", line 275, in __init__
    self.nb1 = ControlNotebook(self, wx.NewIdRef(), style = wx.CLIP_CHILDREN)
  File "/home/allan/Downloads/DEVSimPy/ControlNotebook.py", line 193, in __init__
    GeneralNotebook.__init__(self)
  File "/home/allan/Downloads/DEVSimPy/ControlNotebook.py", line 44, in __init__
    propPanel = PropPanel(self, self.labelList[1])
  File "/home/allan/Downloads/DEVSimPy/PropPanel.py", line 36, in __init__
    propSizer.Add(self.defaultPropertiesPage(), 1, wx.EXPAND|wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTRE_VERTICAL, 10)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at /home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/sizer.cpp(2085) in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

I believe that I have everything installed correctly. Any idea on how to fix this?

Kind regards
Allan

**Comment by capocchi** [comment]
Dear Allan,

wxpython has been updated with a new version (4.0.1) (https://discuss.wxpython.org/t/shifting-to-4-1-yes-really/32970) and cause errors in DEVSimPy. I have to work on that in order to push a new release of DEVSimPy (I soon finished!).
Meanwhile, install the 4.0.7post2 version (pip install wxPython==4.0.7post2) of wx which is compatible with DEVSimPy 4.0. 

Best.

**Comment by allanc1** [comment]
Hi
The build of wxPython 4.07 was not successful, but I found that it is included in the Ubuntu package 
python3-wxgtk-media4.0 and I now have a running DEVSimPy.

Thanks for all your patience.

Kind regards
Allan
